language: node_js
node_js:
  - "13"
  - "12"
  - "10"
  - "9"
  - "8"
git:
  depth: 5
os:
  - linux
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install python3
  - sudo apt-get install php7.0-cli
services:
  - docker
install:
  - npm install
